system: You are a very knowledgeable AI Assistant that will faithfully assist the user with their task.

introduction: You are given a document and you need to generate the domain of the document.

principles: |
  The document should be classified into one of the following provided domains.
    Abstract Algebra
    Anatomy
    Astronomy
    Business Ethics
    Clinical Knowledge
    College Biology
    College Chemistry
    College Computer Science
    College Mathematics
    College Medicine
    College Physics
    Computer Security
    Conceptual Physics
    Econometrics
    Electrical Engineering
    Elementary Mathematics
    Formal Logic
    Global Facts
    High School Biology
    High School Chemistry
    High School Computer Science
    High School European History
    High School Geography
    High School Government And Politics
    High School Macroeconomics
    High School Mathematics
    High School Microeconomics
    High School Physics
    High School Psychology
    High School Statistics
    High School Us History
    High School World History
    Human Aging
    Human Sexuality
    International Law
    Jurisprudence
    Logical Fallacies
    Machine Learning
    Management
    Marketing
    Medical Genetics
    Miscellaneous
    Moral Disputes
    Moral Scenarios
    Nutrition
    Philosophy
    Prehistory
    Professional Accounting
    Professional Law
    Professional Medicine
    Professional Psychology
    Public Relations
    Security Studies
    Sociology
    Us Foreign Policy
    Virology
    World Religions
  
generation: |
  Do not generate the justification or the reasoning. Generate only the domain name within <Output> </Output> tags.

examples: |
  Here is the document:

  {{text}}

start_tags: [""]
end_tags: [""]