[project]
name = "my-sdg-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "sdg-hub",
]

[tool.uv.sources]
sdg-hub = { workspace = true }
